// src/pages/galery/Galery.tsx
import { createEffect, createResource, createSignal, Suspense } from 'solid-js';
import CitationWide from '../../components/citation-wide/CitationWide';
import SpiralLoader from '../../components/loaders/SpiralLoader';
import PageHeader from '../../components/page-header/PageHeader';
import Rewards from '../../components/rewards/Rewards';
import { fetchAPI } from '../../modules/api';
import { APIParams } from '../../modules/api_types';
import './galery.scss';

const Galery = () => {
  const urlParamsObject: APIParams = {
    publicationState: 'live',
    populate: '*',
  };
  const [galeries] = createResource(() =>
    fetchAPI('galeries', urlParamsObject)
  );
  const [tiles, setTiles] = createSignal([]);
  createEffect(() => {
    if (!galeries.loading) {
      setTiles(galeries()?.data as any);
    }
  });
  return (
    <div class='galeries'>
      <h2>Mes galeries photo</h2>
      <Suspense fallback={<SpiralLoader></SpiralLoader>}>
        <PageHeader tiles={tiles()}></PageHeader>
      </Suspense>
      <div class='galeries__content'>
        <CitationWide
          text="La photographie devient de l'art quand elle dévoile l'âme et révèle l'authenticité du sujet."
          author='Monique Moreau'
        />
      </div>
      <Rewards></Rewards>
    </div>
  );
};

export default Galery;

// apps/karinelefort-frontend/src/app/galery/galery.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';
@Component({
  selector: 'karinelefort-web-galery',
  templateUrl: './galery.component.html',
  styleUrls: ['./galery.component.scss'],
})
export class GaleryComponent implements OnInit {
  galeries = [];
  isLoaded = false;
  error: unknown;

  async ngOnInit() {
    const config = {
      headers: {Authorization: `Bearer ${'bc4b93a92c4679cfb4f1345af79087a7a52780b91d95172e683b8515cd3f2574a1396dd93a1d316acf26e26fd6d360d5d37a5d72712841f1b1d94f61ab19903c62ac1200cf209f5937a2b406bf51b4c1924c4bd4beb0fef5be51b0f220e374bd6b3cda923475a3a15cb0cb34d522f99d1b82c5b501ce6bb941fa84923c4fa479'}`}
    }
    const filters = "publicationState=live&filters[is_private][$ne]=true&populate=Previsualisation";
      try {
        const res = await axios.get(`http://localhost:1337/api/galeries?${filters}`, config);
        this.galeries = res.data.data;
        this.isLoaded = true;
      } catch (error) {
        this.error = error;
      }
  }
}

<div class="galeries">
  <karinelefort-web-page-header
  *ngIf="isLoaded"
  title="Galeries"
  subtitle="retrouvez mes travaux"
  [tiles]="galeries"
></karinelefort-web-page-header>
  <div class="galeries__content">
    <karinelefort-web-citation-fw
      text="La photographie devient de l'art quand elle dévoile l'âme et révèle l'authenticité du sujet."
      author="Monique Moreau"
    >
    </karinelefort-web-citation-fw>
    <karinelefort-web-rewards></karinelefort-web-rewards>
  </div>
</div>
