// src/pages/private-galeries/PrivateGaleries.tsx
import CtaBanner from '../../components/cta-banner/CtaBanner';
import { For } from 'solid-js';
import './privateGaleries.scss';
function PrivateGaleries() {
  const galeries = [
    {
      title: 'Julie',
      link: '#',
    },
    {
      title: 'Arnaud',
      link: '#',
    },
    {
      title: 'Duchamp',
      link: '#',
    },
    {
      title: 'Luche',
      link: '#',
    },
    {
      title: 'Kempen',
      link: '#',
    },
    {
      title: 'Agathe',
      link: '#',
    },
  ];
  return (
    <div class='private-galeries'>
      <div class='galeries__header'>
        <h1>Vos photos</h1>
        <span>Votre galerie privée suite à une séance avec moi</span>
      </div>
      <ul>
        <For each={galeries}>
          {(galery: any, index) => {
            return (
              <li>
                <div
                  class='private-galery-item fade-in-bck'
                  style={`animation-delay: ${index() * 120}ms`}
                >
                  <span class='lock'></span> {galery.title}
                </div>
              </li>
            );
          }}
        </For>
      </ul>
      <CtaBanner />
    </div>
  );
}

export default PrivateGaleries;

// apps/karinelefort-frontend/src/app/private-galeries/private-galeries.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'karinelefort-web-private-galeries',
  templateUrl: './private-galeries.component.html',
  styleUrls: ['./private-galeries.component.scss'],
})
export class PrivateGaleriesComponent {
  galeries = [
    {
      title: 'Julie',
      link: '#',
    },
    {
      title: 'Arnaud',
      link: '#',
    },
    {
      title: 'Duchamp',
      link: '#',
    },
    {
      title: 'Luche',
      link: '#',
    },
    {
      title: 'Kempen',
      link: '#',
    },
    {
      title: 'Agathe',
      link: '#',
    },
  ];
}

<div class="private-galeries">
  <div class="galeries__header">
    <h1>Vos photos</h1>
    <span>Votre galerie privée suite à une séance avec moi</span>
  </div>
  <ul>
    <li *ngFor="let item of galeries; let i = index">
      <div class="private-galery-item fade-in-bck" [ngStyle]="{'animation-delay': i*120 + 'ms'}">
        <span class="lock"></span> {{ item.title }}
      </div>
    </li>
  </ul>
</div>
