// src/components/page-header/PageHeader.tsx
import { For, Show } from 'solid-js';
import ImageWithTitleOverlay from '../image-with-title-overlay/ImageWithTitleOverlay';
import './pageHeader.scss';
function PageHeader(props: any) {
  return (
    <div class='page__header'>
      <Show when={props.title}>
        <div class='header__title'>
          <h1>{props.title}</h1>
          <span>{props.subtitle}</span>
        </div>
      </Show>
      <div class='header__images'>
        <For each={props.tiles}>
          {(item: any, index) => {
            return (
              <ImageWithTitleOverlay
                title={item['attributes'].Nom.toString()}
                link={item['attributes'].slug.toString()}
                lazy
                imgSrc={item['attributes'].Previsualisation['data']['attributes'].url.toString()}
                delay={index()}
              />
            );
          }}
        </For>
      </div>
    </div>
  );
}

export default PageHeader;

// apps/karinelefort-frontend/src/app/page-header/page-header.component.ts
import { Component, Input} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
@Component({
  selector: 'karinelefort-web-page-header',
  templateUrl: './page-header.component.html',
  styleUrls: ['./page-header.component.scss'],
})
export class PageHeaderComponent {
  @Input() title = '';
  @Input() subtitle = '';
  @Input() tiles:Record<string|number, unknown>[] = [];
  baseRoute = this.route.snapshot.url[0].path;

  constructor(
    private route: ActivatedRoute  ) {}
}

<div class="page__header">
  <div class="header__title">
    <h1>{{title}}</h1>
    <span>{{subtitle}}</span>
  </div>
  <div class="header__images">
    <karinelefort-web-image-with-title-overlay
      *ngFor="let item of tiles; let i = index"
      [title]="item['attributes'].Nom.toString()"
      [link]="baseRoute + '/' + item['attributes'].slug.toString()"
      [imgSrc]="'http://localhost:1337'+item['attributes'].Previsualisation['data']['attributes'].url.toString()"
      [delay]="i"
    >
  </karinelefort-web-image-with-title-overlay>
  </div>
</div>
