// src/components/full-width-img-with-outline/FullWidthImgWithOutline.tsx
import { Component } from 'solid-js';
import './full-width-img-with-outline.scss';

const FullWidthImgWithOutline: Component = (props: any) => {
  return (
    <div class='img__container'>
      <div class='img__inner'></div>
      <div
        class='img__img fade-in-left'
        style={`background-image: url(${props.imgUrl}`}
      ></div>
    </div>
  );
};

export default FullWidthImgWithOutline;

// apps/karinelefort-frontend/src/app/full-width-img-with-outline/full-width-img-with-outline.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'karinelefort-web-full-width-img-with-outline',
  templateUrl: './full-width-img-with-outline.component.html',
  styleUrls: ['./full-width-img-with-outline.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FullWidthImgWithOutlineComponent {
  @Input() imgUrl = ""
}

<div class="img__container">
  <div class="img__inner"></div>
  <div
    class="img__img fade-in-left"
    [ngStyle]="{ 'background-image': 'url('+'http://localhost:1337' + imgUrl }"
    alt=""
  ></div>
  <div class="img__tail"></div>
</div>
